### ISSUE TITLE
LexV2BotLocaleIds = "ko_KR" don't work

### ISSUE THREAD

**Issue by fromcloud** [aws-solutions/aws-qnabot#391]
**Describe the bug**
When I set the LexV2BotLocaleIds variable to "ko_KR", stack deployment fail.
- Status Reason : Received response status [FAILED] from custom resource : Message returned : "ko_KR"

**To Reproduce**
Set LexV2BotLocaleIds variable to value including "ko_KR" like "en_US,es_US,fr_CA,ko_KR".
Deploy qnabot stack.

**Expected behavior**
Successful deployment.

**Please complete the following information about the solution:**
- [ ] Version: 5.1.0 ( (SO0189) QnABot with admin and client websites - (Master v5.1.0) )

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![image](https://user-images.githubusercontent.com/11764522/150643015-524e2572-9fc9-4982-a1fa-23a0e4d2b2a3.png)

**Additional context**
Setting LexV2BotLocaleIds as "ja_JP", stack is successfully deployed.

**Comment by froguin** [comment]
I think this may cause the problem:
https://github.com/aws-solutions/aws-qnabot/blob/main/lambda/lexv2-build/handler.py

When lambda "QnABot-Lexv2BotLambda" runs to translate slot type values, there're no ko_KR defines like in LEXV2_BOT_LOCALE_VOICE
`LEXV2_BOT_LOCALE_VOICES = {
	"de_DE": "Hans",
	"en_AU": "Nicole",
	"en_GB": "Amy",
	"en_US": "Joanna",
	"es_419": "Mia",
	"es_ES": "Conchita",
	"es_US": "Lupe",
	"fr_CA": "Chantal",
	"fr_FR": "Mathieu",
	"it_IT": "Bianca",
	"ja_JP": "Mizuki"
}`

**Comment by jjk-dev** [comment]
Do not put ko_KR in LexV2BotLocaleIds variable and deploy with just default settings. Then go to content designer website and change setting - "enable_multi_language_support" parameter to "true". If you refresh client page then lex will understand Korean by using Amazon Translate.

**Comment by froguin** [comment]
Lex occurred a build failure in Korean languate version. I think some utterances that type is AMAZON.AlphaNumeric caused internal build failure in CloudFormation Template. 

https://docs.aws.amazon.com/lexv2/latest/dg/howitworks-builtins-slots.html
- AMAZON.AlphaNumeric type supported all locales except Korean

**Comment by rajc-aws** [comment]
Thanks for raising this issue, and sorry for the delay in responding back. 

This was addressed as part of QnABot release 5.1.1. 
More details: https://github.com/aws-solutions/aws-qnabot/blob/main/CHANGELOG.md#511---2022-02-04

Closing this issue.
